### ISSUE TITLE
Module does not work with symlinked media folder

### ISSUE THREAD

**Issue by ProxiBlue** [cloudinary/cloudinary_magento#28] opened 2018-03-20 08:53 UTC
In magento it is very common to have the media folder as a symlink, pointing to a shared resource of images.
This is common in a multi-server setup where images are shared across servers.

In admin, when adding images to CMS pages, the storage thumbnails do not work, as the incorrect REAL path is passed as the image url, which is incorrect.

To reproduce the problem:

* In your magento base folder move the media folder to a new folder called 'media_REAL' ```mv ./media ./media_REAL```
* symlink that to the magento_REAL folder as media: ```ln -s ./media_REAL ./media

You will have a folder setup as such:

![selection_152](https://user-images.githubusercontent.com/4994260/37644410-a7dbe22a-2c5e-11e8-823f-95330d2a254c.png)

Access magento admin, and attempt to insert an image into the cms content area.
You will find none of the thumbnails show:

![selection_153](https://user-images.githubusercontent.com/4994260/37644478-eee2ad70-2c5e-11e8-87e7-3a99c7f2b2ee.png)

Checking given paths:

![selection_154](https://user-images.githubusercontent.com/4994260/37644509-0b65804e-2c5f-11e8-9cbe-0f08c40769a5.png)

notice the usage of ```media_REAL``` which makes the image path incorrect.
Expected would simply be ```/media/```

This is a serious issue, and is requiring disabling of teh module, as our content staff cannot work on content, effectively stopping site work.

We are thus paying for a service we cannot use. Please attend urgently.

**Comment by idobarnoam** [comment] 2018-03-20 13:06
Hey @ProxiBlue,

The module indeed currently does not support symlinked folders, like you describe.

There is an open request with our dev team to support this as well. I would be happy to let you know as soon as this is implemented.

If at all possible the immediate workaround would be to use the media folder directly.

**Comment by ProxiBlue** [comment] 2018-03-20 13:37
Unfortunately we use a cluster where front-end servers are spun up as resources are required. This requires a shared media environment, and cannot be changed. 

Do you have any estimate when this will be fixed? Weeks, months, years?

**Comment by idobarnoam** [comment] 2018-03-20 14:10
Hi

We currently don't have an ETA for the implementation.

I've spoken with our product and dev team regarding this in order to make sure its being looked at.

I will let you when there are any new insights regarding this.

**Comment by ProxiBlue** [comment] 2018-03-20 22:54
Hi, 

Thank you for your feedback. 
Can you enlighten me to when the noted open request to your Dev team was created? 

Are we talking days/weeks/months/years ago?

**Comment by idobarnoam** [comment] 2018-03-21 14:43
Hi @ProxiBlue,

This was recently raised and was opened last week.

Our dev team would review it and see what is the best approach to implement a solution.

I will keep you updated on insights as they happen

**Comment by ProxiBlue** [comment] 2018-03-21 22:04
Thanks.

**Comment by ProxiBlue** [comment] 2018-05-04 01:51
@idobarnoam 

In your last response you noted:

> This was recently raised and was opened last week.

However, I just found https://github.com/cloudinary/cloudinary_magento/issues/15

which seems to be the same issue. There is even a PR submitted (https://github.com/cloudinary/cloudinary_magento/pull/14) which aparently fixes teh issue.

So, woudl seem this bug has been here since 2016? and still not fixed?

**Comment by idobarnoam** [comment] 2018-05-07 13:41
Hi @ProxiBlue 

Thanks for bringing this to our attention.

Symlinks are working when using auto upload and migrating images manually. This has been in place just recently.
We did manage to reproduce the issue you are describing which affects the wysiwyg editor with symlinked folders. This was handled in the past internally since the specific PR you reference had some conflicts that were never resolved.  Later versions affected the fix, and we would look into this.

A specific request to look into this was opened again and I'll update the thread when there are any new insights regarding this.

I apologize for the confusion.

**Comment by idobarnoam** [comment] 2019-12-22 14:15
@ProxiBlue we're closing this as this was handled on the above PR

Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

Thanks!

**Closed by idobarnoam** 2019-12-22 14:15 UTC
Labels: enhancement
