### ISSUE TITLE
Cloudinary is Useless in the CMS Pages!

### ISSUE THREAD

**Issue by IbrahimS2** [cloudinary/cloudinary_magento#50] opened 2019-05-21 00:11 UTC
We should have parameters/configurations to define the "w_" and "h_" as well; currently, we can only apply universal parameters/configurations.

We could be using this as an efficient way to add the proper width that is taken from the browser/device: https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/rias

**Comment by idobarnoam** [comment] 2019-05-22 08:47
Hi @MageSuper 
The module does offer to allow specific transformation to specific products.

If you go to each product you could see a "Cloudinary" menu where you can then apply a specific transformation to that product.

Are you seeing something else?
If so could you share the version number of both your Magento installation and Cloudinary module?

Regarding responsive images, although the module indeed does not support that natively it's on our road map to allow that.

**Comment by MageSuper** [comment] 2019-05-23 15:21
@idobarnoam I am referring to the CMS page not the product nor the category page! In the CMS page, you insert the images as they are, and they will be transformed on the page load, my issue is I cannot assign fixed width & height in the transformation to the homepage for example!

Therefore I tried this approach: https://cloudinary.com/documentation/responsive_images#step_2_set_the_img_tag_parameters

But this would not work, as it would set the w_ and the h_ parameters after loading the initial images, even with lazy loading, the images above the fold will load twice, the first time upon loading the page, the second time upon changing the parameters!


I hope I made myself clear in this regard.

**Comment by idobarnoam** [comment] 2019-05-26 11:40
@MageSuper Thanks for clarifying.

If I understand you correctly you are referring to adding new images to static pages, right?
Would you be able to elaborate on the flow that you perfroming so could pinpoint the issue and see how we can best help?

You could also open a request at support@cloudinary.com to preserve privacy

**Comment by MageSuper** [comment] 2019-06-03 02:48
@idobarnoam For example, we have this HTML markup:
```
<picture>
    <source media="(min-width: 997px)" data-srcset="{{media url='wysiwyg/test1260x400.png'}}" />
    <source media="(min-width: 768px)" data-srcset="{{media url='wysiwyg/test800x400.png'}}" />
    <source media="(max-width: 599px)" data-srcset="{{media url='wysiwyg/test600x300.png'}}" />
    <img class="lazyload cld-responsive" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="{{media url='wysiwyg/test1260x400.png'}}" alt="">
</picture>
```

The issue is by applying what you suggesting in the official documentation: https://cloudinary.com/documentation/responsive_images#step_2_set_the_img_tag_parameters

I will have to add the following to the homepage specifically:
```
<script type="text/javascript">
    var cl = cloudinary.Cloudinary.new({cloud_name: "demo"}); 
    // replace 'demo' with your cloud name in the line above 
    cl.responsive();
</script>
```

Now by doing that we end up with a couple of problems and a confusion:

1. Why would we define the Cloudinary account name when we have it integrated as an extension?
2. Even if we do that, it would not be a practical solution, as the moment the page renders it will load the original images then after 1-2secs it will initialise the mentioned script to pass the right parameters based on the device height/width which means it will load over again which means we will end up loading the same images/banners twice?
3. Therefore the only solution I could think of is to extend Magento variable **{{media url=''}}** which means we will have something like **{{media cl="w_400, h_400" url=""}}** or by extending Cloudinary with a native lazyloader that triggers the browser to send the right data prior loading the images.

Let me know your thoughts in this regard.

**Comment by idobarnoam** [comment] 2019-06-06 11:00
Hi @MageSuper 

1. Currently, the Magento plugin does not natively support responsive design. The solution offered here would be on top of the Magento implementation. This would indeed require setting the Cloudinary configuration for this solution.
2+3. It's possible to leave the `src` attribute empty to have no image loaded until the right image is being delivered. would that work in your use case?

**Comment by MageSuper** [comment] 2019-06-06 11:22
@idobarnoam Not really, as that would create an issue from the user experience point of view, plus it would still load and then it would change the parameters afterword which means it will load the same images twice!

**Comment by idobarnoam** [comment] 2019-06-11 15:47
@MageSuper When leaving the `src` attribute empty the browser would display an icon until our script is called and loads the image based on the dimension of the rectangle. There would be no additional image loaded in this case
If you don't want to display a different image or have no image until the browser runs our script then you could try a different approach to responsive design by using the `srcset` and `sizes`attribute as described in the post: https://cloudinary.com/blog/responsive_images_with_srcset_sizes_and_cloudinary

Note that this would also involve editing the page manually.

Does that make sense?

**Comment by eyalktCloudinary** [comment] 2020-09-09 13:03
Closing due to time elapsed.

**Closed by eyalktCloudinary** 2020-09-09 13:03 UTC
